# Generated by Django 4.2.2 on 2023-07-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='isCurrent',
            field=models.BooleanField(default=True),
        ),
    ]
